// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.AsyncErrHdl;

import com.sybase.automation.framework.core.helper.VPHelper;

/**
 * Script Name   : <b>AsyncErrHdl_Notification_ErrorScreen3</b><br>
 * Generated     : <b>2012/03/16 10:42:58 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  March 16, 2012
 * @author test
 */
public abstract class AsyncErrHdl_Notification_ErrorScreen3Helper extends VPHelper
{
	

	protected AsyncErrHdl_Notification_ErrorScreen3Helper()
	{
		setScriptName("testscript.Workflow.AsyncErrHdl.AsyncErrHdl_Notification_ErrorScreen3");
	}
	
}

