// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.AsyncErrHdl;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>AsyncErrHdl_SubmitWF_From2</b><br>
 * Generated     : <b>2012/03/21 8:04:32 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  March 21, 2012
 * @author flvxp
 */
public abstract class AsyncErrHdl_SubmitWF_From2Helper extends RationalTestScript
{
	

	protected AsyncErrHdl_SubmitWF_From2Helper()
	{
		setScriptName("testscript.Workflow.AsyncErrHdl.AsyncErrHdl_SubmitWF_From2");
	}
	
}

