// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.StartPoint;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>SP_Auto_Create_Screen_Activate</b><br>
 * Generated     : <b>2011/09/09 2:43:07 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  September 09, 2011
 * @author eric
 */
public abstract class SP_Auto_Create_Screen_ActivateHelper extends RationalTestScript
{
	

	protected SP_Auto_Create_Screen_ActivateHelper()
	{
		setScriptName("testscript.Workflow.StartPoint.SP_Auto_Create_Screen_Activate");
	}
	
}

