// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.StartPoint;

import com.sybase.automation.framework.core.helper.VPHelper;

/**
 * Script Name   : <b>SP_Activate_DB_str</b><br>
 * Generated     : <b>2011/09/02 12:12:13 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  September 02, 2011
 * @author eric
 */
public abstract class SP_Activate_DB_strHelper extends VPHelper
{
	

	protected SP_Activate_DB_strHelper()
	{
		setScriptName("testscript.Workflow.StartPoint.SP_Activate_DB_str");
	}
	
}

