// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.TupleSupport;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>Tuple_DynamicChc_to_DynamicChc_1_E2E</b><br>
 * Generated     : <b>2011/11/04 10:03:56 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  November 04, 2011
 * @author ffan
 */
public abstract class Tuple_DynamicChc_to_DynamicChc_1_E2EHelper extends RationalTestScript
{
	

	protected Tuple_DynamicChc_to_DynamicChc_1_E2EHelper()
	{
		setScriptName("testscript.Workflow.TupleSupport.Tuple_DynamicChc_to_DynamicChc_1_E2E");
	}
	
}

