// DO NOT EDIT: This file is automatically generated each time the script is modified.
// To modify this file either use 'Insert Java Code Snippet'or 'Insert Java Method' 
// option from simplified script.
package testscript.Workflow.SAPDemo;
import resources.testscript.Workflow.SAPDemo.SAPDemoHelper;
import testscript.Workflow.cfg.Cfg;

import com.rational.test.ft.*;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.value.*;
import com.rational.test.ft.vp.*;
import component.entity.EE;
import component.entity.MBOProperties;
import component.entity.MainMenu;
import component.entity.PropertiesView;
import component.entity.WFScreen;
import component.entity.WN;
import component.entity.WorkFlow;
import component.entity.WorkFlowEditor;
import component.entity.WFCustomizer.WFClientResult;
import component.entity.WFCustomizer.WFCustomizer;
import component.entity.customJsGenerator.CustomJsTestScript;
import component.entity.model.DeployOption;
import component.entity.model.LoadArgument;
import component.entity.model.MBOAttribute;
import component.entity.model.Modifications;
import component.entity.model.SAPCP;
import component.entity.model.SAPMBO;
import component.entity.model.SAPOperation;
import component.entity.model.WFScreenMenuItem;
import component.entity.model.WorkFlowPackage;
import component.entity.resource.RC;
import component.entity.resource.SAP;
import component.view.Problems;

/**
 * Description   : Functional Test Script
 * @author yangg
 */
public class SAPDemo extends SAPDemoHelper
{	
	/**
	 * Script Name   : <b>SAPDemo</b>
	 * Generated     : <b>Mar 6, 2012 6:38:19 PM</b>
	 * Description   : Functional Test Script
	 * Original Host : WinNT Version 5.1  Build 2600 (S)
	 * 
	 * @since  2012/03/06
	 * @author yangg
	 */
	public void testMain(Object[] args) 
	{ 	

//		EE.createSAPCP(new SAPCP(RC.getResource(SAP.class)).name("sap"), true);
		WN.useProject(Cfg.projectName);
		WN.createMbo(new SAPMBO().startParameter(Cfg.projectName)
				.dataSourceType("SAP")
				.name("Bank")
				.connectionProfile("sap")
				.operation("Application Components->Cross-Application Components->Bank->Bank,GetList")
				.parameter("BANK_CTRY,in")
				.parameter("BANK_LIST,out")
//				.parameter("BANK_LIST,in")
				.parameterValue("BANK_CTRY,IN"));
		
		WN.addSAPOperation(new SAPOperation().startParameter(WN.mboPath(Cfg.projectName, "Bank"))
				.type("CREATE")
				.name("create")
				.operation("Application Components->Cross-Application Components->Bank->Bank,Create")
				.parameter("BANK_ADDRESS,in")
				.parameter("BANK_CTRY,in")
				.parameter("BANK_KEY,in")
				
                .parameterValue("BANK_CTRY,IN")
                .parameterValue("BANK_KEY,INDUSIND")
//              
//                .parameterValue("BAPI_BANK_CREATE_BANK_ADDRESS->BANK_NAME,INDUSIND BANK")
//                .parameterValue("BAPI_BANK_CREATE_BANK_ADDRESS->REGION,WE")
//                .parameterValue("BAPI_BANK_CREATE_BANK_ADDRESS->STREET,425 DB Marg ")
//                .parameterValue("BAPI_BANK_CREATE_BANK_ADDRESS->CITY,Mumbai")
//                .parameterValue("BAPI_BANK_CREATE_BANK_ADDRESS->BANK_GROUP,IN")
//                .parameterValue("BAPI_BANK_CREATE_BANK_ADDRESS->POBK_CURAC,A")
//                .parameterValue("BAPI_BANK_CREATE_BANK_ADDRESS->SWIFT,12565099")
//                .parameterValue("BAPI_BANK_CREATE_BANK_ADDRESS->BANK_NO,123423")
//                .parameterValue("BAPI_BANK_CREATE_BANK_ADDRESS->BANK_BRANCH,NRE")
//                .parameterValue("BAPI_BANK_CREATE_BANK_ADDRESS->ADDR_NO,12")
                );
		
		MainMenu.saveAll();	
		
		WN.deployProject(new DeployOption().startParameter(WN.mboPath(Cfg.projectName, "Bank"))
				.server("My Unwired Server")
				.mode(DeployOption.MODE_REPLACE)
				.serverConnectionMapping("sap,sap")
				);
		
		//create WF..
		WN.createWorkFlow(new WorkFlow().startParameter(Cfg.projectName)
				.name(Cfg.wfName)
				.option(WorkFlow.SP_CLIENT_INIT)
				);	
		WorkFlowEditor.dragMbo(Cfg.projectName, "Bank");
		
		WorkFlowEditor.addMenuItem("Start", new WFScreenMenuItem().name("Open GetList_create")
				.type("Online Request")
				.project(Cfg.projectName)
				.mbo("Bank")
				.defaultSuccessScreen("Bankcreate")
				);
//		WorkFlowEditor.setMenuItem("Bankcreate", new WFScreenMenuItem().name("Create")
//				.defaultSuccessScreen(""));		
				
		WFCustomizer.runTest(new WorkFlowPackage().startParameter(WN.filePath(Cfg.projectName, Cfg.wfName))
				.deployToServer("true")
				.unwiredServer("My Unwired Server")
				.assignToUser(testscript.Workflow.cfg.Cfg.deviceUser), 
				customJsTestScript(),
				testscript.Workflow.cfg.Cfg.tplanscript_C);
				
//		WFCustomizer.verifyResult(new WFClientResult().data(
//				"id=Bank_BANK_CTRY_attribKey,value=IN|"));	
	}

	private CustomJsTestScript customJsTestScript() {
		CustomJsTestScript s = new CustomJsTestScript();
		s.screen("Start").moveTo("Bankcreate").throughMenuItem("Open GetList_create");
		s.screen("Bankcreate").setData("GetList_create_BANK_NAME_paramKey", "INDUSIND BANK");
		s.screen("Bankcreate").setData("GetList_create_REGION_paramKey", "WE");
		s.screen("Bankcreate").setData("GetList_create_STREET_paramKey", "425 DB Marg ");
		s.screen("Bankcreate").setData("GetList_create_CITY_paramKey", "Mumbai");
		s.screen("Bankcreate").setData("GetList_create_SWIFT_CODE_paramKey", "12565099");
		s.screen("Bankcreate").setData("GetList_create_BANK_GROUP_paramKey", "IN");
		s.screen("Bankcreate").setData("GetList_create_POBK_CURAC_paramKey", "A");
		s.screen("Bankcreate").setData("GetList_create_BANK_CTRY_paramKey", "IN");
		s.screen("Bankcreate").setData("GetList_create_BANK_KEY_paramKey", "INDUSIND");
		
		
		s.screen("Bankcreate").moveTo("Start").throughMenuItem("Create");
		
		return s;
	}
}
		