// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Customization;

import com.sybase.automation.framework.core.helper.VPHelper;

/**
 * Script Name   : <b>Cust_Overwrite_2</b><br>
 * Generated     : <b>2012/03/20 10:05:18 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  March 20, 2012
 * @author test
 */
public abstract class Cust_Overwrite_2Helper extends VPHelper
{
	

	protected Cust_Overwrite_2Helper()
	{
		setScriptName("testscript.Workflow.Customization.Cust_Overwrite_2");
	}
	
}

