// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.EmailInjection;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>EmailInjection_All</b><br>
 * Generated     : <b>2010/10/24 9:57:36 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  October 24, 2010
 * @author ffan
 */
public abstract class EmailInjection_AllHelper extends com.sybase.automation.framework.core.helper.BatchExecutionSuperClass
{
	

	protected EmailInjection_AllHelper()
	{
		setScriptName("testscript.Workflow.EmailInjection.EmailInjection_All");
	}
	
}

