// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Deploy;

import com.sybase.automation.framework.core.helper.BatchExecutionSuperClass;

/**
 * Script Name   : <b>Deploy_all</b><br>
 * Generated     : <b>2012/01/31 1:58:45 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  January 31, 2012
 * @author eric
 */
public abstract class Deploy_allHelper extends BatchExecutionSuperClass
{
	

	protected Deploy_allHelper()
	{
		setScriptName("testscript.Workflow.Deploy.Deploy_all");
	}
	
}

