// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Deploy;

import com.sybase.automation.framework.core.helper.VPHelper;

/**
 * Script Name   : <b>DPLY_PKG_Create_Err_1</b><br>
 * Generated     : <b>2011/09/29 7:35:21 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  September 29, 2011
 * @author eric
 */
public abstract class DPLY_PKG_Create_Err_1Helper extends VPHelper
{
	

	protected DPLY_PKG_Create_Err_1Helper()
	{
		setScriptName("testscript.Workflow.Deploy.DPLY_PKG_Create_Err_1");
	}
	
}

