// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Deploy;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh</b><br>
 * Generated     : <b>2012/02/11 2:31:35 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  February 11, 2012
 * @author ffan
 */
public abstract class hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhHelper extends RationalTestScript
{
	/**
	 * ImageCombo: with default state.
	 *		.mappableClassIndex : 0
	 * 		.class : com.sybase.uep.xbw.util.ImageCombo
	 * 		.priorLabel : Client icon:
	 * 		.classIndex : 0
	 */
	protected ScrollTestObject imageCombo() 
	{
		return new ScrollTestObject(
                        getMappedTestObject("imageCombo"));
	}
	/**
	 * ImageCombo: with specific test context and state.
	 *		.mappableClassIndex : 0
	 * 		.class : com.sybase.uep.xbw.util.ImageCombo
	 * 		.priorLabel : Client icon:
	 * 		.classIndex : 0
	 */
	protected ScrollTestObject imageCombo(TestObject anchor, long flags) 
	{
		return new ScrollTestObject(
                        getMappedTestObject("imageCombo"), anchor, flags);
	}
	
	/**
	 * ImageCombo: with default state.
	 *		.mappableClassIndex : 0
	 * 		.class : com.sybase.uep.xbw.util.ImageCombo
	 * 		.priorLabel : Client icon:
	 * 		.classIndex : 0
	 */
	protected ScrollTestObject imageCombo2() 
	{
		return new ScrollTestObject(
                        getMappedTestObject("imageCombo2"));
	}
	/**
	 * ImageCombo: with specific test context and state.
	 *		.mappableClassIndex : 0
	 * 		.class : com.sybase.uep.xbw.util.ImageCombo
	 * 		.priorLabel : Client icon:
	 * 		.classIndex : 0
	 */
	protected ScrollTestObject imageCombo2(TestObject anchor, long flags) 
	{
		return new ScrollTestObject(
                        getMappedTestObject("imageCombo2"), anchor, flags);
	}
	
	/**
	 * Table: with default state.
	 *		.mappableClassIndex : 0
	 * 		.class : org.eclipse.swt.widgets.Table
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject table() 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("table"));
	}
	/**
	 * Table: with specific test context and state.
	 *		.mappableClassIndex : 0
	 * 		.class : org.eclipse.swt.widgets.Table
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject table(TestObject anchor, long flags) 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("table"), anchor, flags);
	}
	
	/**
	 * Table: with default state.
	 *		.mappableClassIndex : 0
	 * 		.class : org.eclipse.swt.widgets.Table
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject table2() 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("table2"));
	}
	/**
	 * Table: with specific test context and state.
	 *		.mappableClassIndex : 0
	 * 		.class : org.eclipse.swt.widgets.Table
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject table2(TestObject anchor, long flags) 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("table2"), anchor, flags);
	}
	
	

	protected hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhHelper()
	{
		setScriptName("testscript.Workflow.Deploy.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh");
	}
	
}

