// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.CallActionOutSideMenu;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>CallAction_CancelScreen_General</b><br>
 * Generated     : <b>2012/03/13 12:48:00 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  March 13, 2012
 * @author eric
 */
public abstract class CallAction_CancelScreen_GeneralHelper extends RationalTestScript
{
	

	protected CallAction_CancelScreen_GeneralHelper()
	{
		setScriptName("testscript.Workflow.CallActionOutSideMenu.CallAction_CancelScreen_General");
	}
	
}

