// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.CallActionOutSideMenu;

import com.sybase.automation.framework.core.helper.VPHelper;

/**
 * Script Name   : <b>CallAction_SaveScreen_ParaMap</b><br>
 * Generated     : <b>2012/03/07 7:32:11 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  March 07, 2012
 * @author eric
 */
public abstract class CallAction_SaveScreen_ParaMapHelper extends VPHelper
{
	

	protected CallAction_SaveScreen_ParaMapHelper()
	{
		setScriptName("testscript.Workflow.CallActionOutSideMenu.CallAction_SaveScreen_ParaMap");
	}
	
}

