// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Designer_Prop;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>D_673801_Matching_Rule_Tooling</b><br>
 * Generated     : <b>2012/02/09 5:30:40 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  February 09, 2012
 * @author ffan
 */
public abstract class D_673801_Matching_Rule_ToolingHelper extends RationalTestScript
{
	

	protected D_673801_Matching_Rule_ToolingHelper()
	{
		setScriptName("testscript.Workflow.Designer_Prop.D_673801_Matching_Rule_Tooling");
	}
	
}

