// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Credential;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>RoleMapping_Query_Mapped_Valid</b><br>
 * Generated     : <b>2011/10/22 1:54:29 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  October 22, 2011
 * @author flvxp
 */
public abstract class RoleMapping_Query_Mapped_ValidHelper extends RationalTestScript
{
	

	protected RoleMapping_Query_Mapped_ValidHelper()
	{
		setScriptName("testscript.Workflow.Credential.RoleMapping_Query_Mapped_Valid");
	}
	
}

