DROP TABLE IF EXISTS DiffTZ
CREATE TABLE dba.DiffTZ (
a INT NOT NULL, 
b TIME NULL, 
c DATE NULL, 
d datetime NULL, 
e TIMESTAMP NULL, 
)
IN SYSTEM
;
ALTER TABLE dba.DiffTZ 
 ADD CONSTRAINT ASA122 PRIMARY KEY CLUSTERED (a)
;