// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.AllKindOfMbo;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.sybase.automation.framework.core.helper.BatchExecutionSuperClass;

/**
 * Script Name   : <b>AllkindOfMbo_all</b><br>
 * Generated     : <b>2012/02/04 4:34:47 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  February 04, 2012
 * @author ffan
 */
public abstract class AllkindOfMbo_allHelper extends BatchExecutionSuperClass
{
	

	protected AllkindOfMbo_allHelper()
	{
		setScriptName("testscript.Workflow.AllkindOfMbo.AllkindOfMbo_all");
	}
	
}

