// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.AllKindOfMbo;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>M_631322_NQ_One2One_E2E_1</b><br>
 * Generated     : <b>2012/03/04 10:18:38 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  March 04, 2012
 * @author min zhao
 */
public abstract class M_631322_NQ_One2One_E2E_1Helper extends RationalTestScript
{
	

	protected M_631322_NQ_One2One_E2E_1Helper()
	{
		setScriptName("testscript.Workflow.AllKindOfMbo.M_631322_NQ_One2One_E2E_1");
	}
	
}

