// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.OnlineCache;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>OLC_Email_ReturnMulti_part2_E2E</b><br>
 * Generated     : <b>2012/04/11 5:14:34 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  April 11, 2012
 * @author min zhao
 */
public abstract class OLC_Email_ReturnMulti_part2_E2EHelper extends RationalTestScript
{
	

	protected OLC_Email_ReturnMulti_part2_E2EHelper()
	{
		setScriptName("testscript.Workflow.OnlineCache.OLC_Email_ReturnMulti_part2_E2E");
	}
	
}

