// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.OnlineCache;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.sybase.automation.framework.core.helper.VPHelper;

/**
 * Script Name   : <b>OLC_WFWizard_ExtractPara</b><br>
 * Generated     : <b>2011/10/12 2:09:29 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  October 12, 2011
 * @author eric
 */
public abstract class OLC_WFWizard_ExtractParaHelper extends VPHelper
{
	

	protected OLC_WFWizard_ExtractParaHelper()
	{
		setScriptName("testscript.Workflow.OnlineCache.OLC_WFWizard_ExtractPara");
	}
	
}

