// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.OnlineCache;

import com.sybase.automation.framework.core.helper.BatchExecutionSuperClass;

/**
 * Script Name   : <b>OnlineCache_all</b><br>
 * Generated     : <b>2012/02/12 7:18:40 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  February 12, 2012
 * @author eric
 */
public abstract class OnlineCache_allHelper extends BatchExecutionSuperClass
{
	

	protected OnlineCache_allHelper()
	{
		setScriptName("testscript.Workflow.OnlineCache.OnlineCache_all");
	}
	
}

