// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.ConditionalScreen;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>CdtnSrcNavigate_Edit_Alltypes</b><br>
 * Generated     : <b>2011/11/25 2:26:03 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  November 25, 2011
 * @author ffan
 */
public abstract class CdtnSrcNavigate_Edit_AlltypesHelper extends RationalTestScript
{
	

	protected CdtnSrcNavigate_Edit_AlltypesHelper()
	{
		setScriptName("testscript.Workflow.ConditionalScreen.CdtnSrcNavigate_Edit_Alltypes");
	}
	
}

