// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.ConditionalScreen;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>CdtnScrNavigate_Delete_Basic_01</b><br>
 * Generated     : <b>2011/10/12 10:57:13 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  October 12, 2011
 * @author ffan
 */
public abstract class CdtnScrNavigate_Delete_Basic_01Helper extends RationalTestScript
{
	

	protected CdtnScrNavigate_Delete_Basic_01Helper()
	{
		setScriptName("testscript.Workflow.ConditionalScreen.CdtnScrNavigate_Delete_Basic_01");
	}
	
}

