// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Controls;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>Ctrl_669288_Validate_Time_E2E</b><br>
 * Generated     : <b>2011/12/13 4:39:54 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  December 13, 2011
 * @author ffan
 */
public abstract class Ctrl_669288_Validate_Time_E2EHelper extends RationalTestScript
{
	

	protected Ctrl_669288_Validate_Time_E2EHelper()
	{
		setScriptName("testscript.Workflow.Controls.Ctrl_669288_Validate_Time_E2E");
	}
	
}

