// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Screens;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>CSFO_One2One_N_Cascade_N_bidir_Child</b><br>
 * Generated     : <b>2012/02/10 1:59:50 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  February 10, 2012
 * @author ffan
 */
public abstract class CSFO_One2One_N_Cascade_N_bidir_ChildHelper extends RationalTestScript
{
	

	protected CSFO_One2One_N_Cascade_N_bidir_ChildHelper()
	{
		setScriptName("testscript.Workflow.Screens.CSFO_One2One_N_Cascade_N_bidir_Child");
	}
	
}

