// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Screens;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>DndCMBO_1_1_Composite_N_bi_E2E</b><br>
 * Generated     : <b>2011/09/16 2:32:54 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  September 16, 2011
 * @author eric
 */
public abstract class DndCMBO_1_1_Composite_N_bi_E2EHelper extends RationalTestScript
{
	

	protected DndCMBO_1_1_Composite_N_bi_E2EHelper()
	{
		setScriptName("testscript.Workflow.Screens.DndCMBO_1_1_Composite_N_bi_E2E");
	}
	
}

