// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Screens;

import com.sybase.automation.framework.core.helper.BatchExecutionSuperClass;

/**
 * Script Name   : <b>Screens_all</b><br>
 * Generated     : <b>2012/01/30 6:20:42 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  January 30, 2012
 * @author eric
 */
public abstract class Screens_allHelper extends BatchExecutionSuperClass
{
	

	protected Screens_allHelper()
	{
		setScriptName("testscript.Workflow.Screens.Screens_all");
	}
	
}

