// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Localization;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>Local_cn_ValidateMsg_RT_Android</b><br>
 * Generated     : <b>2011/11/24 10:49:39 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  November 24, 2011
 * @author flvxp
 */
public abstract class Local_cn_ValidateMsg_RT_AndroidHelper extends RationalTestScript
{
	

	protected Local_cn_ValidateMsg_RT_AndroidHelper()
	{
		setScriptName("testscript.Workflow.Localization.Local_cn_ValidateMsg_RT_Android");
	}
	
}

