// DO NOT EDIT: This file is automatically generated each time the script is modified.
// To modify this file either use 'Insert Java Code Snippet'or 'Insert Java Method' 
// option from simplified script.
package testscript.Workflow.Credential;
import resources.testscript.Workflow.Credential.Credential_AllHelper;
import com.rational.test.ft.*;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.value.*;
import com.rational.test.ft.vp.*;

/**
 * Description   : Functional Test Script
 * @author yangg
 */
public class Credential_All extends Credential_AllHelper
{	
	/**
	 * Script Name   : <b>Credential_All</b>
	 * Generated     : <b>May 24, 2012 3:16:19 AM</b>
	 * Description   : Functional Test Script
	 * Original Host : WinNT Version 5.1  Build 2600 (S)
	 * 
	 * @since  2012/05/24
	 * @author yangg
	 */
	public void testMain(Object[] args) 
	{ 	
	
		callScript("testscript.Workflow.Credential.C618608_CachedCredential_Warning");
		callScripts("testscript.Workflow.Credential.Security_Dynamic_E2E*");
		callScripts("testscript.Workflow.Credential.Security_Negative_E2E_Android_01");

							
	}
}
		