// DO NOT EDIT: This file is automatically generated each time the script is modified.
// To modify this file either use 'Insert Java Code Snippet'or 'Insert Java Method' 
// option from simplified script.
package testscript.Workflow.SAP;
import resources.testscript.Workflow.SAP.SAPALLHelper;
import com.sybase.automation.framework.core.helper.*;
import com.rational.test.ft.*;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.value.*;
import com.rational.test.ft.vp.*;

/**
 * Description   : Functional Test Script
 * @author yangg
 */
public class SAPALL extends SAPALLHelper
{	
	/**
	 * Script Name   : <b>SAPALL</b>
	 * Generated     : <b>Mar 14, 2012 10:44:49 PM</b>
	 * Description   : Functional Test Script
	 * Original Host : WinNT Version 5.1  Build 2600 (S)
	 * 
	 * @since  2012/03/14
	 * @author yangg
	 */
	public void testMain(Object[] args) 
	{ 	
		
//		callScripts("testscript.Workflow.SAP.SAP_RLTN_*");
//		callScript("testscript.Workflow.SAP.SAP_TableOut_1_E2E");
//		callScript("testscript.Workflow.SAP.SAP_StructPara_ops_E2E");
//		callScript("testscript.Workflow.SAP.SAP_StructPara_PK_E2E");
//		callScript("testscript.Workflow.SAP.SAP_Simple_AllDT_LoadPara_E2E");
		/**
		 * Have some issue in location on one item, and go to the details Page
		 */
//		callScript("testscript.Workflow.SAP.SAP_Simple_AllDT_PK_E2E");
//		callScript("testscript.Workflow.SAP.SAP_TablePara_ops_1_1_E2E");
//		//Still need to confirm the data of insert operation
//		callScript("testscript.Workflow.SAP.SAP_TablePara_ops_1_2_E2E");
//		callScript("testscript.Workflow.SAP.SAP_TablePara_ops_1_OLC_E2E");
		
//		
//		callScript("testscript.Workflow.SAP.SAP_Simple_AllDT_E2E");
//		callScript("testscript.Workflow.SAP.SAP_TablePara_ops_2_E2E");
//		callScript("testscript.Workflow.SAP.SAP_TablePara_ops_2_OLC_E2E");
//		callScript("testscript.Workflow.SAP.SAP_TablePara_PK_E2E");
//		callScript("testscript.Workflow.SAP.SAP_TablePara_PK_OLC_E2E");
//		callScript("testscript.Workflow.SAP.SAP_Simple_AllDT_E2E");
		callScript("testscript.Workflow.SAP.SAP_RLTN_4_E2E");
		callScript("testscript.Workflow.SAP.SAP_RLTN_3_E2E");

							
	}
}
		