// DO NOT EDIT: This file is automatically generated each time the script is modified.
// To modify this file either use 'Insert Java Code Snippet'or 'Insert Java Method' 
// option from simplified script.
package testscript.Workflow.WS;
import java.util.ArrayList;

import resources.testscript.Workflow.WS.WS_Complex_ParaHelper;
import testscript.Workflow.cfg.Cfg;

import com.rational.test.ft.*;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.value.*;
import com.rational.test.ft.vp.*;
import com.sybase.automation.framework.common.CDBUtil;

import component.entity.EE;
import component.entity.WN;
import component.entity.WorkFlow;
import component.entity.WorkFlowEditor;
import component.entity.WFCustomizer.WFCustomizer;
import component.entity.customJsGenerator.CustomJsTestScript;
import component.entity.model.DeployOption;
import component.entity.model.Operation;
import component.entity.model.SAPCP;
import component.entity.model.SAPMBO;
import component.entity.model.SAPOperation;
import component.entity.model.WFScreenMenuItem;
import component.entity.model.WSCP;
import component.entity.model.WSMBO;
import component.entity.model.WSOperation;
import component.entity.model.WorkFlowPackage;
import component.entity.resource.Criteria;
import component.entity.resource.RC;
import component.entity.resource.SAP;
import component.entity.resource.WS;

/**
 * Description   : Functional Test Script
 * @author yangg
 */
public class WS_Complex_Para extends WS_Complex_ParaHelper
{	
	/**
	 * Script Name   : <b>WS_Complex_Para</b>
	 * Generated     : <b>Apr 11, 2012 8:24:12 PM</b>
	 * Description   : Functional Test Script
	 * Original Host : WinNT Version 5.1  Build 2600 (S)
	 * 
	 * @since  2012/04/11
	 * @author yangg
	 */
	public void testMain(Object[] args) 
	{ 	

        EE.createWSCP(new WSCP(RC.getResource(WS.class, new Criteria().equal("name", "ws_complex"))).name("ws_complex"), true);
		WN.useProject(Cfg.projectName);

		// TODO Insert code here
		WN.createMbo(new WSMBO().startParameter(Cfg.projectName)
				.dataSourceType("Web Service")
				.name("getAlltype")
				.connectionProfile("ws_complex")
				.method("alltypeporttype:getAllType")
				);

		WN.addWSOperation(new WSOperation().startParameter(WN.mboPath(Cfg.projectName, "getAlltype"))
				.type("CREATE")
				.name("create")
				.method("alltypeporttype:insertAllType")							
				);
		
		WN.deployProject(new DeployOption().startParameter(WN.mboPath(Cfg.projectName, "getAlltype"))
				.server("My Unwired Server")
				.serverConnectionMapping("ws_complex,ws_complex")
				);
		
		WN.createWorkFlow(new WorkFlow().startParameter(Cfg.projectName)
				.name(Cfg.wfName)
				.option(WorkFlow.SP_CLIENT_INIT)
				);	

		WorkFlowEditor.dragMbo(Cfg.projectName, "getAlltype");
		
		WorkFlowEditor.addMenuItem("Start", new WFScreenMenuItem().name("Open getAlltype")
			.type("Online Request")
			.project(Cfg.projectName)
			.mbo("getAlltype")
			.objectQuery("findAll")
			.defaultSuccessScreen("getAlltype")
			);
		WorkFlowEditor.addMenuItem("getAlltype", new WFScreenMenuItem().name("Create")
				.type("Open")
				.screen("getAlltypecreate")
				);

		WorkFlowEditor.setMenuItem("getAlltypecreate",  new WFScreenMenuItem().name("Create")
				.defaultSuccessScreen("getAlltype")
				);
		
		WFCustomizer.runTest(new WorkFlowPackage().startParameter(WN.filePath(Cfg.projectName, Cfg.wfName))
				.deployToServer("true")
				.unwiredServer("My Unwired Server")
				.assignToUser(testscript.Workflow.cfg.Cfg.deviceUser), 
				customJsTestScript(),
				testscript.Workflow.cfg.Cfg.tplanscript_C);
		
		java.util.List<String> clause = new ArrayList<String>();
		clause.add("IntType=120");
		clause.add("StringType='WE test'");
		vpManual("dbresult", 1, CDBUtil.getRecordCount(Cfg.hostName, Cfg.projectName, "getAlltype", clause)).performTest();
							
	}
	
	private CustomJsTestScript customJsTestScript() {
		CustomJsTestScript s = new CustomJsTestScript();
//		s.screen("Start").moveTo("getAlltypecreate").throughMenuItem("Open getAlltypecreate");
		s.screen("Start").moveTo("getAlltype").throughMenuItem("Open getAlltype");
		s.screen("getAlltype").moveTo("getAlltypecreate").throughMenuItem("Create");
		s.screen("getAlltypecreate").setData("getAlltype_create_IntType_paramKey", "120");
		s.screen("getAlltypecreate").setData("getAlltype_create_StringType_paramKey", "WE test");
		
		
		s.screen("getAlltypecreate").moveTo("getAlltype").throughMenuItem("Create");
		
		return s;
	}
}
		