// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Actions;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>A683365_ACT_Menu_Items_Name_Negative</b><br>
 * Generated     : <b>2011/10/12 8:16:50 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  October 12, 2011
 * @author flvxp
 */
public abstract class A683365_ACT_Menu_Items_Name_NegativeHelper extends RationalTestScript
{
	

	protected A683365_ACT_Menu_Items_Name_NegativeHelper()
	{
		setScriptName("testscript.Workflow.Actions.A683365_ACT_Menu_Items_Name_Negative");
	}
	
}

