// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Actions;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.sybase.automation.framework.core.helper.VPHelper;

/**
 * Script Name   : <b>ACT_Actions</b><br>
 * Generated     : <b>2011/09/26 5:55:25 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  September 26, 2011
 * @author flvVm
 */
public abstract class ACT_ActionsHelper extends VPHelper
{
	

	protected ACT_ActionsHelper()
	{
		setScriptName("testscript.Workflow.Actions.ACT_Actions");
	}
	
}

