// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Actions;

import com.sybase.automation.framework.core.helper.BatchExecutionSuperClass;

/**
 * Script Name   : <b>Action_all</b><br>
 * Generated     : <b>2012/02/01 7:23:29 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  February 01, 2012
 * @author eric
 */
public abstract class Action_allHelper extends BatchExecutionSuperClass
{
	

	protected Action_allHelper()
	{
		setScriptName("testscript.Workflow.Actions.Action_all");
	}
	
}

