// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.Actions;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>One2One_E2E_Act_TwoUpdate_Android</b><br>
 * Generated     : <b>2011/10/26 2:58:12 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  October 26, 2011
 * @author flvxp
 */
public abstract class One2One_E2E_Act_TwoUpdate_AndroidHelper extends RationalTestScript
{
	

	protected One2One_E2E_Act_TwoUpdate_AndroidHelper()
	{
		setScriptName("testscript.Workflow.Actions.One2One_E2E_Act_TwoUpdate_Android");
	}
	
}

