// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.WF_ErrorHandle;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>ErrorMessage_1_3</b><br>
 * Generated     : <b>2012/01/12 10:20:28 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  January 12, 2012
 * @author ffan
 */
public abstract class ErrorMessage_1_3Helper extends RationalTestScript
{
	

	protected ErrorMessage_1_3Helper()
	{
		setScriptName("testscript.Workflow.WF_ErrorHandle.ErrorMessage_1_3");
	}
	
}

