// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.testscript.Workflow.WF_ErrorHandle;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>Improved_ErrorMsg_4</b><br>
 * Generated     : <b>2011/10/14 3:27:10 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 2 <br>
 * 
 * @since  October 14, 2011
 * @author ffan
 */
public abstract class Improved_ErrorMsg_4Helper extends RationalTestScript
{
	

	protected Improved_ErrorMsg_4Helper()
	{
		setScriptName("testscript.Workflow.WF_ErrorHandle.Improved_ErrorMsg_4");
	}
	
}

